{"cert_user_id": "ivesen@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065895, "title": "file synchronization/updating failing", "body": "ok, I just want to preface this by saying it's one of those awful errors that seem to be OS dependent, and exactly how it manifests itself is seemingly random.\r\nthe error is that for some zites (a steadily climbing amount) I can't sync/update all files, I looked through the debug log and found that this error seems to be related and affect a large number of files ( or the same ones many times)\r\n`[2017-05-04 17:21:04,513] ERROR    Site:1MeFqF..q7nH Json merged-ZeroMe/12h51ug6CcntU2aiBjhP8Ns2e5VypbWWtv/data/users/1BR2d8kCqCBaFWLQ9KXnNbJzLmcPJ3DdTL/data.json load error: OperationalError: attempt to write a readonly database in SiteStorage.py line 234 > MutePlugin.py line 100 > SiteStorage.py line 74 > Db.py line 323 > DbCursor.py line 49`\r\n\r\nattached is my entire debug log, hope to have this resolved soon.\r\n\r\n[debuglog.txt](https://github.com/HelloZeroNet/ZeroNet/files/977387/debuglog.txt)\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1493916621, "modified": 1502888718, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/923", "source_type": "github"}], "next_comment_id": 3, "comment": {"1604065895_mirrored_ivesen_github": [{"comment_id": 1, "body": "that should be impossible since zeronet is the only thing that accesses that folder,\r\nunless some absolute asshat made a daemon that indexes all my files and changes their permissions.\r\nI'll look into whether I can get an audit log as to what might be happening, but I'm not sure if I can at that level.\r\n\r\nedit: I noticed earlier that using chown helps a bit, is it possible that zeronet writes as the wrong user ?\r\nedit 2: I should note that this problem affects a random selection of files (based on observation)\r\nedit 3: it looks like audit logs will have to wait for next week, since I'll have to change kernels.", "added": 1493928353, "modified": 1493929734, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/923#issuecomment-299333206", "source_type": "github"}, {"comment_id": 2, "body": "no, the issue is still unresolved.\r\nI've done a few attempts at finding out why it happens, so far the only thing I found is that zeronet sometimes attempts to open too many files at once. I somewhat doubt that's related however.\r\n\r\nedit: I've seen multiple reports of the same issue across zeronet after reporting this issue, it appears to affect windows and linux. (uncertain about osx) ", "added": 1502881540, "modified": 1502888718, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/923#issuecomment-322782145", "source_type": "github"}]}}