{"cert_user_id": "bufgix@github", "next_topic_id": 2, "topic": [{"topic_id": 1604067487, "title": "UnicodeDecodeError when start ZeroNet.", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version:  0.7.0 r4197\r\n  * Python version: 3.6.7\r\n  * Operating system: Windows 10 x64\r\n  * Web browser: OperaGX core: 62.0.3331.132\r\n  * Tor status: not available\r\n  * Opened port: no\r\n  * Special configuration: Pipenv virtual management \r\n  * System Lang: Turkish\r\n\r\n### Step 2: Describe the problem:\r\nI getting unhandled exception(UnicodeDecodeError)\r\n```bash\r\nC:\\Users\\simplex\\py_projects\\ZeroNet (py3 -> origin)\r\n(ZeroNet-iAvXUjmi) \u03bb python zeronet.py\r\n- Starting ZeroNet...\r\n[15:42:44] - Libsecpk256k1 loaded: FFILibrary_C:\\Users\\simplex\\.virtualenvs\\ZeroNet-iAvXUjmi\\lib\\site-packages\\coincurve\\libsecp256k1.dll in 0.226s\r\n[15:42:44] - Version: 0.7.0 r4197, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)], Gevent: 1.4.0\r\n[15:42:44] - Creating FileServer....\r\n[15:42:44] - Creating UiServer....\r\n[15:42:44] SiteManager Deleting orphan site from content.db: 1MgHVPCE1ve6QfKrgsqCURzRj72HrRWioz\r\n[15:42:44] - Removing old SSL certs...\r\n[15:42:44] - Starting servers....\r\n[15:42:44] Ui.UiServer --------------------------------------\r\n[15:42:44] Ui.UiServer Web interface: http://127.0.0.1:43110/\r\n[15:42:44] Ui.UiServer --------------------------------------\r\n[15:42:44] - Unhandled exception: [(<class 'UnicodeDecodeError'>, UnicodeDecodeError('utf-8', b'Sistem belirtilen yolu bulam\\x8dyor.', 28, 29, 'invalid start byte'), <traceback object at 0x000001CBFF506188>)]\r\nTraceback (most recent call last):\r\n  File \"src\\gevent\\greenlet.py\", line 766, in gevent._greenlet.Greenlet.run\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\plugins\\AnnounceLocal\\AnnounceLocalPlugin.py\", line 133, in start\r\n    return super(FileServerPlugin, self).start(*args, **kwargs)\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\File\\FileServer.py\", line 349, in start\r\n    ConnectionServer.start(self)\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\Connection\\ConnectionServer.py\", line 82, in start\r\n    CryptConnection.manager.loadCerts()\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\Crypt\\CryptConnection.py\", line 105, in loadCerts\r\n    if self.createSslRsaCert() and \"tls-rsa\" not in self.crypt_supported:\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\Crypt\\CryptConnection.py\", line 140, in createSslRsaCert\r\n    back = proc.stdout.read().strip().decode().replace(\"\\r\", \"\")\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 28: invalid start byte\r\n[15:42:49] Ui.UiServer Added 127.0.0.1:43110 as allowed host\r\n[15:42:50] Site:1MgHVP..Wioz Rebuilding db...\r\n[15:42:50] Site:1MgHVP..Wioz Creating tables...\r\n[15:42:50] Db:NullPaste Table keyvalue outdated...version: False need: 2, rebuilding...\r\n[15:42:50] Db:NullPaste Table json outdated...version: 0 need: 2, rebuilding...\r\n[15:42:50] Db:NullPaste Table paste outdated...version: 0 need: 2, rebuilding...\r\n[15:42:50] Db:NullPaste Table comment outdated...version: 0 need: 1, rebuilding...\r\n[15:42:50] Site:1MgHVP..Wioz Getting db files...\r\n[15:42:50] Site:1MgHVP..Wioz [MISSING] data-default/users/content-default.json\r\n[15:42:50] Site:1MgHVP..Wioz Importing data...\r\n[15:42:50] Site:1MgHVP..Wioz Imported 0 data file in 0.002s\r\n```\r\nBut ZeroNet working correctly.\r\n\r\n#### Observed Results:\r\n  * Got unhandled exception\r\n\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1567418152, "modified": 1567425907, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2180", "source_type": "github"}], "next_comment_id": 4, "comment": {"1604067487_mirrored_bufgix_github": [{"comment_id": 1, "body": "> `openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config src/lib/openssl/openssl.cnf -subj \"/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon\" -keyout data/cakey-rsa.pem -out data/cacert-rsa.pem -batch` \r\n\r\nI getting an error in this command\r\n```bash\r\n(ZeroNet-iAvXUjmi) \u03bb openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config src/lib/openssl/openssl.cnf -subj \"/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon\" -keyout data/cakey-rsa.pem -out data/cacert-rsa.pem -batch\r\nreq: Error on line 57 of config file \"src/lib/openssl/openssl.cnf\"\r\nGenerating a RSA private key\r\n....................................................................................+++++\r\n...............+++++\r\nwriting new private key to 'data/cakey-rsa.pem'\r\n-----\r\nunable to find 'distinguished_name' in config\r\nproblems making Certificate Request\r\n12208:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto\\conf\\conf_lib.c:270:\r\n```\r\nmy environment property OPENSSL_CONF is\r\n```bash\r\n(ZeroNet-iAvXUjmi) \u03bb echo %OPENSSL_CONF%\r\nD:\\Programs\\OpenSSL-Win64\\bin\\openssl.cfg\r\n```\r\nand problem still persists\r\n```bash\r\nC:\\Users\\simplex\\py_projects\\ZeroNet (py3 -> origin)\r\n(ZeroNet-iAvXUjmi) \u03bb python zeronet.py --debug\r\n[...]\r\n[16:56:59] - Current maxstdio: 512, changing to 2048...\r\n[16:56:59] CryptConnectionManager Generating RSA CAcert and CAkey PEM files...\r\n[16:56:59] CryptConnectionManager Running: \"tools\\openssl\\openssl.exe\" req -new -newkey rsa:2048 -days 3650 -nodes -x509 -config \"src/lib/openssl/openssl.cnf\" -subj \"/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA\" -keyout \"./data/cakey-rsa.pem\" -out \"./data/cacert-rsa.pem\" -batch\r\n[16:56:59] - Unhandled exception\r\nTraceback (most recent call last):\r\n  File \"src\\gevent\\greenlet.py\", line 766, in gevent._greenlet.Greenlet.run\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\plugins\\AnnounceLocal\\AnnounceLocalPlugin.py\", line 133, in start\r\n    return super(FileServerPlugin, self).start(*args, **kwargs)\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\File\\FileServer.py\", line 349, in start\r\n    ConnectionServer.start(self)\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\Connection\\ConnectionServer.py\", line 82, in start\r\n    CryptConnection.manager.loadCerts()\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\Crypt\\CryptConnection.py\", line 105, in loadCerts\r\n    if self.createSslRsaCert() and \"tls-rsa\" not in self.crypt_supported:\r\n  File \"C:\\Users\\simplex\\py_projects\\ZeroNet\\src\\Crypt\\CryptConnection.py\", line 140, in createSslRsaCert\r\n    back = proc.stdout.read().strip().decode().replace(\"\\r\", \"\")\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 28: invalid start byte\r\n[16:56:59] SiteManager Saved sites in 0.01s (generate: 0.00s, write: 0.01s)\r\n[16:56:59] SiteManager Updated merger sites in 0.000s\r\n[16:56:59] Site:1Gfey7..fcdp Start downloading, bad_files: {'content.json': 6}, check_size: True, blind_includes: True\r\n[16:56:59] Site:1Gfey7..fcdp Need content.json first\r\n[16:56:59] BroadcastServer Started on port 1544\r\n[...]\r\n```\r\n", "added": 1567421959, "modified": 1567422171, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2180#issuecomment-527158274", "source_type": "github"}, {"comment_id": 2, "body": "````python\r\nstdout = proc.stdout.read()\r\nprint(\"-->  \", stdout)\r\nback = proc.stdout.read().strip().decode().replace(\"\\r\", \"\")\r\n````\r\nOutput:\r\n```bash\r\n(ZeroNet-iAvXUjmi) \u03bb python zeronet.py\r\n- Starting ZeroNet...\r\n[17:12:50] - Libsecpk256k1 loaded: FFILibrary_C:\\Users\\simplex\\.virtualenvs\\ZeroNet-iAvXUjmi\\lib\\site-packages\\coincurve\\libsecp256k1.dll in 0.106s\r\n[17:12:50] - Version: 0.7.0 r4197, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)], Gevent: 1.4.0\r\n[17:12:50] - Creating FileServer....\r\n[17:12:50] - Creating UiServer....\r\n[17:12:50] SiteManager Deleting orphan site from content.db: 1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp\r\n[17:12:50] - Removing old SSL certs...\r\n[17:12:50] - Starting servers....\r\n[17:12:50] Ui.UiServer --------------------------------------\r\n[17:12:50] Ui.UiServer Web interface: http://127.0.0.1:43110/\r\n[17:12:50] Ui.UiServer --------------------------------------\r\n-->   b'Sistem belirtilen yolu bulam\\x8dyor.\\r\\n'\r\n[17:12:50] CryptConnectionManager RSA ECC SSL CAcert generation failed, CAcert or CAkey files not exist. ()\r\n[17:12:52] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection\r\n[17:12:55] PeerPortchecker Checking port 34885 (ipv4) using checkPortchecker result: {'ip': '37.130.123.6', 'opened': False} in 2.433s\r\n[17:12:55] PeerPortchecker Trying to open port using UpnpPunch...\r\n[17:12:58] PeerPortchecker Checking port 34885 (ipv4) using checkPortchecker result: {'ip': '37.130.123.6', 'opened': False} in 1.845s\r\n[17:12:58] ConnServer Server port opened ipv4: False, ipv6: None\r\n```\r\n\r\nI understand. This problem is related to my system language. ` b'Sistem belirtilen yolu bulam\\x8dyor.\\r\\n'` mean `The system cannot find the path specified.`. Classic TR chars problem :/\r\n\r\nbut as I said, ZeroNet working correctly.", "added": 1567423213, "modified": 1567423439, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2180#issuecomment-527164884", "source_type": "github"}, {"comment_id": 3, "body": "```bash\r\n(ZeroNet-iAvXUjmi) \u03bb python zeronet.py\r\n- Starting ZeroNet...\r\n[18:00:23] - Libsecpk256k1 loaded: FFILibrary_C:\\Users\\simplex\\.virtualenvs\\ZeroNet-iAvXUjmi\\lib\\site-packages\\coincurve\\libsecp256k1.dll in 0.106s\r\n[18:00:24] - Version: 0.7.0 r4200, Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)], Gevent: 1.4.0\r\n[18:00:24] - Creating FileServer....\r\n[18:00:24] - Creating UiServer....\r\n[18:00:24] SiteManager Deleting orphan site from content.db: 1Gfey7wVXXg1rxk751TBTxLJwhddDNfcdp\r\n[18:00:24] - Removing old SSL certs...\r\n[18:00:24] - Starting servers....\r\n[18:00:24] Ui.UiServer --------------------------------------\r\n[18:00:24] Ui.UiServer Web interface: http://127.0.0.1:43110/\r\n[18:00:24] Ui.UiServer --------------------------------------\r\n[18:00:24] CryptConnectionManager RSA ECC SSL CAcert generation failed, CAcert or CAkey files not exist. (b'Sistem belirtilen yolu bulam\\x8dyor.')\r\n[18:00:26] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection\r\n[18:00:29] PeerPortchecker Checking port 34885 (ipv4) using checkPortchecker result: {'ip': '37.130.123.6', 'opened': False} in 2.645s\r\n```\r\nlooks good.", "added": 1567425749, "modified": 1567425749, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2180#issuecomment-527177739", "source_type": "github"}]}}