{"cert_user_id": "simplefreelife@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065672, "title": "I cannot access Zeronet", "body": "> Sorry, My english level Is Low,I use administrator privileges in the windows command console running zeronet.cmd about 30 seconds after the following results. I really need your help. Thank you very much!\r\n\r\nDownloading https://github.com/HelloZeroNet/ZeroNet/archive/master.zip to ZeroNet directory.\r\nTraceback (most recent call last):\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\runpy.py\", line 162, in _run_module_as_main\r\n    \"__main__\", fname, loader, pkg_name)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\site-packages\\zerobundle\\run.py\", line 46, in <module>\r\n    download(url, target_dir)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\site-packages\\zerobundle\\run.py\", line 6, in download\r\n    file = urllib.urlopen(url)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\urllib.py\", line 87, in urlopen\r\n    return opener.open(url)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\urllib.py\", line 213, in open\r\n    return getattr(self, name)(url)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\urllib.py\", line 443, in open_https\r\n    h.endheaders(data)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\httplib.py\", line 997, in endheaders\r\n    self._send_output(message_body)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\httplib.py\", line 850, in _send_output\r\n    self.send(msg)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\httplib.py\", line 812, in send\r\n    self.connect()\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\httplib.py\", line 1208, in connect\r\n    HTTPConnection.connect(self)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\httplib.py\", line 793, in connect\r\n    self.timeout, self.source_address)\r\n  File \"D:\\Program Files\\ZeroBundle\\Python\\lib\\socket.py\", line 571, in create_connection\r\n    raise err\r\nIOError: [Errno socket error] [Errno 10060]", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1483676808, "modified": 1492102261, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/745", "source_type": "github"}], "next_comment_id": 2, "comment": {"1604065672_mirrored_simplefreelife_github": [{"comment_id": 1, "body": "> Thanks HelloZeroNet reply. this zipped file solves the problem i'm having with the theme.\r\n\r\nNow, zeronet.cmd successfully downloaded ZeroNet folder. But not as smooth as imagined.\r\nby default, zeronet.cmd generates the ZeroNet floder in the current directory. which causers the following two commands to fail.\r\nhttps://github.com/HelloZeroNet/ZeroBundle/blob/master/zeronet.cmd#L12 \r\nhttps://github.com/HelloZeroNet/ZeroBundle/blob/master/zeronet.cmd#L14\r\nof course, this problem may only exist for me, my method is to use text to open zeronet.cmd and modify line 12 and 14.\r\n\r\n> line12:\r\n\r\n`\t\t..\\Python\\python.exe ..\\ZeroNet\\zeronet\\start.py`\r\n\r\n> line14:\r\n\r\n`\t\t..\\Python\\python.exe ..\\ZeroNet\\zeronet\\zeronet.py %*`\r\nOK, My Chrome browser successfully pops up the hello zeronet page.\r\nIt seems to be going well now, and thanks again to the author and the person who helped me.\r\n", "added": 1483753330, "modified": 1483753458, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/745#issuecomment-271062582", "source_type": "github"}]}}