{"cert_user_id": "YSHZdive@github", "next_topic_id": 2, "topic": [{"topic_id": 1604067040, "title": "UiServer.py error after update", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.6.4 rev3741\r\n  * Operating system: windows 8.1\r\n  * Web browser: firefox\r\n  * Tor status: says available\r\n  * Opened port: no\r\n  * Special configuration: no\r\n\r\n### Step 2: Describe the problem:\r\n`Err: AttributeError: 'module' object has no attribute 'inet_pton' in UiServer.py line 106 > UiRequest.py line 112 > UiRequest.py line 87 > UiRequest.py line 67`\r\n#### Steps to reproduce:\r\n\r\n  1. open 127.1.0.0:43110 after update\r\n\r\n#### Observed Results:\r\n\r\nno result returned, but an error shows up\r\n\r\n#### Expected Results:\r\n\r\nshow the main page\r\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1545186243, "modified": 1545211571, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1828", "source_type": "github"}], "next_comment_id": 2, "comment": {"1604067040_mirrored_YSHZdive_github": [{"comment_id": 1, "body": "Python version - 2.7, bundled.", "added": 1545194595, "modified": 1545194595, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1828#issuecomment-448499411", "source_type": "github"}]}}