{"cert_user_id": "scpketer@github", "next_topic_id": 2, "topic": [{"topic_id": 1604067841, "title": "Zeronet not working on archlinux", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.7.1-1\r\n  * Operating system: archlinux x86_64 (linux kernel ver. 5.5.8)\r\n  * Web browser: chromium\r\n  * Tor status: not available (no config parameter defined in /etc/zeronet.conf)\r\n  * Opened port: yes\r\n\r\n#### Steps to reproduce:\r\n\r\n  1. Install package `zeronet` from AUR\r\n  2. Start `zeronet.service`\r\n  3. Open `127.0.0.1:43110` and observe infinite loading\r\n  4. Check `systemctl status zeronet` and observe `UiWSGIHandler error` messages\r\n(full log follows)\r\n```\r\n\u043c\u0430\u0440 11 17:05:34 keterzarch systemd[1]: Started Decentralized websites using Bitcoin crypto and the BitTorrent network.\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - Libsecp256k1 load failed: No module named '_cffi_backend', try to load OpenSSL\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - OpenSSL loaded: <CDLL 'libssl.so.1.1', handle 55d6dd1fd1d0 at 0x7f2e7e61ea60>, version: 01010104F in 0.028s\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - Version: 0.7.0 r4206, Python 3.8.2 (default, Feb 26 2020, 22:21:03)\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [GCC 9.2.1 20200130], Gevent: 1.4.0\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - Creating FileServer....\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] FileServer Getting random port in range 10000-40000...\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] FileServer Found unused random port: 28060\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - Creating UiServer....\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - Removing old SSL certs...\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] - Starting servers....\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] Ui.UiServer --------------------------------------\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] Ui.UiServer Web interface: http://127.0.0.1:43110/\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] Ui.UiServer --------------------------------------\r\n\u043c\u0430\u0440 11 17:05:35 keterzarch zeronet[55961]: [17:05:35] TorManager Disabling Tor, because error while accessing Tor proxy at port 127.0.0.1:9050: No connection\r\n\u043c\u0430\u0440 11 17:05:37 keterzarch zeronet[55961]: [17:05:37] PeerPortchecker Checking port 28060 (ipv4) using checkPortchecker result: {'ip': '185.145.57.246', 'opened': False} in 2.018s\r\n\u043c\u0430\u0440 11 17:05:37 keterzarch zeronet[55961]: [17:05:37] PeerPortchecker Trying to open port using UpnpPunch...\r\n\u043c\u0430\u0440 11 17:05:39 keterzarch zeronet[55961]: [17:05:39] PeerPortchecker Checking port 28060 (ipv4) using checkPortchecker result: {'ip': '185.145.57.246', 'opened': False} in 1.862s\r\n\u043c\u0430\u0440 11 17:05:39 keterzarch zeronet[55961]: [17:05:39] ConnServer Server port opened ipv4: False, ipv6: None\r\n\u043c\u0430\u0440 11 17:06:38 keterzarch zeronet[55961]: [17:06:38] Ui.UiServer Added 127.0.0.1:43110 as allowed host\r\n\u043c\u0430\u0440 11 17:06:38 keterzarch zeronet[55961]: [17:06:38] - UiWSGIHandler error: AttributeError: module 'cgi' has no attribute 'parse_qsl' in UiServer.py line 41 > pywsgi.py line 923 > UiServer.py line 98\r\n\u043c\u0430\u0440 11 17:06:38 keterzarch zeronet[55961]: [17:06:38] - UiWSGIHandler error: AttributeError: module 'cgi' has no attribute 'parse_qsl' in UiServer.py line 41 > pywsgi.py line 923 > UiServer.py line 98\r\n\u043c\u0430\u0440 11 17:12:34 keterzarch zeronet[55961]: [17:12:34] - UiWSGIHandler error: AttributeError: module 'cgi' has no attribute 'parse_qsl' in UiServer.py line 41 > pywsgi.py line 923 > UiServer.py line 98\r\n\u043c\u0430\u0440 11 17:12:34 keterzarch zeronet[55961]: [17:12:34] - UiWSGIHandler error: AttributeError: module 'cgi' has no attribute 'parse_qsl' in UiServer.py line 41 > pywsgi.py line 923 > UiServer.py line 98\r\n```\r\n\r\n#### Observed Results:\r\n\r\n  Webpage loading took ages (and it didn't load); error messages seen in zeronet service logs.\r\n\r\n#### Expected Results:\r\n\r\nI expected to see a zeronet welcome webpage? It redirected me from `/` to `1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D` but it didn't load in any acceptible time.", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1583921504, "modified": 1590272031, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2472", "source_type": "github"}], "next_comment_id": 2, "comment": {"1604067841_mirrored_scpketer_github": [{"comment_id": 1, "body": "Marked it out-of-date.", "added": 1583935801, "modified": 1583935801, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2472#issuecomment-597755813", "source_type": "github"}]}}