{"cert_user_id": "JayBrown@github", "next_comment_id": 7, "comment": {"1604064916_mirrored_Porco-Rosso_github": [{"comment_id": 1, "body": "From what the IPFS developers said, IPFS does support dynamic content. As for TOR or VPN etc., IPFS works flawlessly on top of that, as ZeroNet does.\n", "added": 1461934247, "modified": 1461934247, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/150#issuecomment-215771715", "source_type": "github"}], "1604065090_mirrored_jarlarntzen_github": [{"comment_id": 2, "body": "OS X 10.11.3, SIP disabled, additional installation of python in /usr/local, pip-installed gevent & msgpack-python (without the -m option), updated all pip-installed formulas, added zeronet, no problems. Works great (Safari 9.0.3). Also works fine with VPN (OpenVPN via built-in utun.)\n", "added": 1457029114, "modified": 1457041602, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/286#issuecomment-191968735", "source_type": "github"}, {"comment_id": 3, "body": "From ZeroNet's web GUI, right?\n", "added": 1461934106, "modified": 1461934106, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/286#issuecomment-215770156", "source_type": "github"}], "1604065150_mirrored_JayBrown_github": [{"comment_id": 4, "body": "I'd first like to see what the problem is before chickening out. Here's the error report after running it manually in the shell:\n\nCrashed Thread:        0  Dispatch queue: com.apple.main-thread\n\nException Type:        EXC_BAD_INSTRUCTION (SIGILL)\nException Codes:       0x0000000000000001, 0x0000000000000000\n\nThread 0 Crashed:: Dispatch queue: com.apple.main-thread\n0   corecext.so                     0x000000010179ec85 initcorecext + 19669\n\nThread 0 crashed with X86 Thread State (64-bit):\n  rax: 0x00000001017a26d0  rbx: 0x000000010174e390  rcx: 0x000000010173fea8  rdx: 0x000000010173b000\n  rdi: 0x0000000000000088  rsi: 0x0000000000000f98  rbp: 0x0000000000000079  rsp: 0x00007fff5ea851f0\n   r8: 0x00000001017317e8   r9: 0x00000000ffffff80  r10: 0x0000000000000600  r11: 0x0000000000000000\n  r12: 0x00000001017317e8  r13: 0x56004951db03fdb1  r14: 0x0000000101670560  r15: 0x0000000101752b50\n  rip: 0x000000010179ec85  rfl: 0x0000000000010202  cr2: 0x000000010179e217\n\nLogical CPU:     0\nError Code:      0x00000000\nTrap Number:     6\n", "added": 1457379452, "modified": 1457379452, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/330#issuecomment-193487518", "source_type": "github"}, {"comment_id": 5, "body": "Probably. Python (in /usr/local/bin) is 64bit, as the default one installed with OS X. Couldn't find the error. Maybe the gevent update messed it up. \n\nThe OS X bundle doesn't work either. Doesn't connect to ZeroNet when launching the .app directly in Finder, and launching it from the Terminal (zsh) with the open command I get the following error:\n\nLSOpenURLsWithRole() failed with error -10810 for the file /Applications/ZeroNet/ZeroNet.app.\n", "added": 1457386165, "modified": 1457386165, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/330#issuecomment-193525856", "source_type": "github"}, {"comment_id": 6, "body": "Ah, found the error\u2026 the .app and the included python binary weren't codesigned. I removed them from quarantine, and now it works.\n", "added": 1457387125, "modified": 1457387125, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/330#issuecomment-193530066", "source_type": "github"}]}, "next_topic_id": 3, "topic": [{"topic_id": 1604065118, "title": "ZeroNet for Synology OS with 0bot & local synchronization", "body": "Would be great to have ZeroNet on Synology OS (DSM 6), with options for a configurable bot, and (better yet) to synchronize the ZeroNet data folder on the NAS with the one on the user's local computer, so you could co-share your ZeroNet sites from the NAS as well.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1457041291, "modified": 1506857041, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/307", "source_type": "github"}, {"topic_id": 1604065150, "title": "[BUG] illegal hardware issue (OS X 10.11.3)", "body": "ZeroNet used to work great on OS X 10.11.3 with Safari 9.0.3. But since upgrading pip and gevent to the latest versions a couple of minutes ago, I'm getting the python error message \"illegal hardware instruction\". What's up with that?\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1457304864, "modified": 1457388004, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/330", "source_type": "github"}]}