{"cert_user_id": "da-moon@github", "next_topic_id": 2, "topic": [{"topic_id": 1604066634, "title": "zeronet remote gateway setup", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.6.3 r3550\r\n  * Operating system: ubuntu 16\r\n  * Web browser: chrome\r\n  * Tor status: not available\r\n  * Opened port: ?\r\n  * Special configuration: online serverless cloud\r\n### Step 2: Describe the problem:\r\nI am trying to setup a private zeronet gateway and possibly make it public in the future but for some reason, zeronet client cannot connect. I am using a paperspace machine with static public ip.\r\n#### Steps to reproduce:\r\n\r\npython zeronet.py --ui_ip 0.0.0.0\r\n\r\n#### Observed Results:\r\n\r\n```\r\n- Starting ZeroNet...                                                      \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# curl 184.105.106.108:43110 \r\n[23:09:23] - OpenSSL loaded, version: 01000207F                            \u2502^X^C\r\n[23:09:23] - Version: 0.6.3 r3550, Python 2.7.12 (default, Dec  4 2017, 14:\u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# curl 184.105.106.108:43110\r\n50:18)                                                                     \u2502curl: (7) Failed to connect to 184.105.106.108 port 43110: Connection timed\r\n[GCC 5.4.0 20160609], Gevent: 1.1.0                                        \u2502 out\r\n[23:09:23] - Creating FileServer....                                       \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# ping 184.105.106.108:43110^\r\n[23:09:23] - Creating UiServer....                                         \u2502C\r\n[23:09:23] - Removing old SSL certs...                                     \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# ^C\r\n[23:09:23] - Starting servers....                                          \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# ^C\r\n[23:09:23] Ui.UiServer --------------------------------------              \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# ^C\r\n[23:09:23] Ui.UiServer Web interface: http://0.0.0.0:43110/                \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# ^C\r\n[23:09:23] Ui.UiServer --------------------------------------              \u2502root@ps79tsyk3:/home/paperspace/ZeroNet-master# \r\n[23:09:24] TorManager Connecting to Tor Controller 127.0.0.1:9051          \u2502\r\n[23:09:24] TorManager Tor controller connect error: error: [Errno 111] Conn\u2502\r\nection refused in TorManager.py line 190 > _socket2.py line 228            \u2502\r\n[23:09:24] TorManager Disabling Tor, because error while accessing Tor prox\u2502\r\ny at port 127.0.0.1:9050: No connection                                    \u2502\r\n[23:09:25] ConnServer Checking port 29647 using portchecker.co...          \u2502\r\n[23:09:26] ConnServer [BAD :(] Port closed: Port 29647 is closed.          \u2502\r\n[23:09:26] ConnServer Trying to open port using UpnpPunch...               \u2502\r\n[23:09:36] ConnServer UpnpPunch run error: UpnpError: Failed to communicate\u2502\r\n with igd using port 29647 on local machine after 3 tries. in FileServer.py\u2502\r\n line 117 > UpnpPunch.py line 349 > UpnpPunch.py line 340  \r\n```\r\n\r\n#### Expected Results:\r\n\r\n  * What did you expect to happen?\r\nconnect to network", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1534551531, "modified": 1534607691, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1509", "source_type": "github"}]}