{
	"next_post_id": 2,
	"next_comment_id": 3,
	"next_follow_id": 1,
	"avatar": "generate",
	"user_name": "Anonymoose",
	"hub": "12h51ug6CcntU2aiBjhP8Ns2e5VypbWWtv",
	"intro": "Random ZeroNet user",
	"post": [],
	"post_like": {
		"1Dg6peqnLM18odQJZxDb2tEUNgAChwfdRT_1561892059": 1561898427
	},
	"comment": [
		{
			"comment_id": 2,
			"body": "I can remove a site from the blocklist, to fix this in `plugins/Multiuser/MultiuserPlugin.py` add:\n\n\n```\n    def actionSiteblockRemove(self, to, site_address):\n        return self.response(to, {\"error\": \"Forbidden: Not allow on proxy\"})\n```\n\n\nIn `class UiWebsocketPlugin(object):`\n\nYou'll have to indent it correctly\n\n---\n\nEDIT: Hm, maybe you run an outdated client? `siteblockRemove` shouldn't be allowed already, it should be present in a list if you search for `self.multiuser_denied_cmds` in `plugins/Multiuser/MultiuserPlugin.py`",
			"post_uri": "1Dg6peqnLM18odQJZxDb2tEUNgAChwfdRT_1561892059",
			"date_added": 1561899447
		}
	],
	"follow": []
}