{"cert_user_id": "nicolas161@github", "next_topic_id": 2, "topic": [{"topic_id": 1604066502, "title": "Segmentation fault", "body": "Operating system: Linaro 2011.07 (Linux)\r\nPython version: 2.7.2\r\nDevice: Kobo Glo HD\r\nKernel version (uname -r): 3.0.35+\r\nShell: /bin/ash\r\n\r\nI have installed both python2.7 and the required packages (msgpack-python python-gevent) following the installation instructions. However, when running python zeronet.py inside the zeronet folder, I get a segmentation fault.\r\n\r\nThese are the last lines in the output of python -v zeronet.py:\r\n\r\n> ./zeronet/src/lib/pyelliptic:\r\n> ##/usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py\r\n> import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc\r\n> ##/usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py\r\n> import abc # precompiled from /usr/lib/python2.7/abc.pyc\r\n> ##/usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py\r\n> import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc\r\n> import _weakref # builtin\r\n> ##/usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py\r\n> import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc\r\n> ##/usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py\r\n> import traceback # precompiled from /usr/lib/python2.7/traceback.pyc\r\n> ##/usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py\r\n> import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc\r\n> ##/usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py\r\n> import re # precompiled from /usr/lib/python2.7/re.pyc\r\n> ##/usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py\r\n> import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc\r\n> import _sre # builtin\r\n> ##/usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py\r\n> import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc\r\n> ##/usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py\r\n> import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc\r\n> import encodings # directory /usr/lib/python2.7/encodings\r\n> ##/usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py\r\n> import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc\r\n> ##/usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py\r\n> import codecs # precompiled from /usr/lib/python2.7/codecs.pyc\r\n> import _codecs # builtin\r\n> ##/usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py\r\n> import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc\r\n> ##/usr/lib/python2.7/encodings/ascii.pyc matches /usr/lib/python2.7/encodings/ascii.py\r\n> import encodings.ascii # precompiled from /usr/lib/python2.7/encodings/ascii.pyc\r\n> Python 2.7.2 (default, Feb  4 2012, 12:18:06) \r\n> [GCC 4.4.5] on linux2\r\n> Type \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n> -Starting ZeroNet...\r\n> ##/mnt/onboard/.kobo/zeronet/src/main.pyc has bad mtime\r\n> Segmentation fault\r\n\r\n(Single '#' signs have been changed to '##' in order to stop triggering some annoying auto-formatting).\r\n\r\nSince I am a python noob, I have no idea what the problem can be here. I was wondering if any of you python wizards know what is happening?", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1524465954, "modified": 1526972327, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1402", "source_type": "github"}]}