{"cert_user_id": "casept@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065411, "title": "Sidebar does not load", "body": "Whenever I try to pull out the sidebar an error message appears.\nThe message is as follows:\n\n`Internal error: TypeError: unsupported operand type(s) for /: 'float' and 'str'\nUiWebsocket.py line 98 > UiWebsocket.py line 175 > SidebarPlugin.py line 432 > SidebarPlugin.py line 211`\n\nThis happens on several zerosites, both on an alpine linux (edge distribution) and a debian linux (testing distribution) based docker container, and happens both on amd64 and armv7 devices.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1471321917, "modified": 1472572272, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/536", "source_type": "github"}], "next_comment_id": 7, "comment": {"1604065411_mirrored_casept_github": [{"comment_id": 1, "body": "ZeroHello (the site which opens automatically) for example.\n", "added": 1471333430, "modified": 1471333430, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/536#issuecomment-240067908", "source_type": "github"}, {"comment_id": 2, "body": "Seems to be fixed now, closing.\n", "added": 1472572272, "modified": 1472572272, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/536#issuecomment-243541338", "source_type": "github"}], "1604065456_mirrored_vishnuhariam_github": [{"comment_id": 3, "body": "Note that some mobile providers utilize carrier grade NAT and therefore you can't forward the port (at least not without hacking their networking equipment).\n", "added": 1474040321, "modified": 1474040321, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/571#issuecomment-247675828", "source_type": "github"}], "1604065473_mirrored_aitorpazos_github": [{"comment_id": 4, "body": "tor probably shouldn't be run in the same container as zeronet. Also, not running ZN as root within the container should be considered.\n", "added": 1474214374, "modified": 1474214458, "source_link": "https://github.com/HelloZeroNet/ZeroNet/pull/585#issuecomment-247866380", "source_type": "github"}], "1604065493_mirrored_yangleitj_github": [{"comment_id": 5, "body": "Seems like an instance of ZN is already running on that port. Try a different port.\n", "added": 1475500657, "modified": 1475500657, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/601#issuecomment-251151539", "source_type": "github"}], "1604065592_mirrored_SergeyDjam_github": [{"comment_id": 6, "body": "cd into the install directory, then do this: `python2 /path/to/directory/containing/zeronet/zeronet.py --data_dir ~/data --log_dir ~/logs`. For some reason the code is picky regarding the directory you are in when you run it.", "added": 1480416347, "modified": 1480416404, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/682#issuecomment-263573582", "source_type": "github"}]}}