{"cert_user_id": "anoduck@github", "next_topic_id": 2, "topic": [{"topic_id": 1604067291, "title": "VerifyError: Content too large: in main.py line 198 > ContentManager.py line 736 > ContentManager.py line 841", "body": "### Step 1: Please describe your environment\r\n\r\n  * ZeroNet version: 0.6.5\r\n  * Operating system: Ubuntu Disco\r\n  * Web browser: Firefox 67.0 && Firefox Dev.\r\n  * Tor status: enabled && always\r\n  * Opened port: yes\r\n  * Special configuration: N/A\r\n\r\n### Step 2: Describe the problem:\r\n\r\nWhen attempting to sign my site I receive the following error:\r\n\r\n`VerifyError: Content too large 99999999B > 10485760B, aborting task... in main.py line 198 > ContentManager.py line 736 > ContentManager.py line 841`\r\n\r\n#### Steps to reproduce:\r\n\r\n  1. Have a large site\r\n  2. Attempt to sign it.\r\n  3. Receive error\r\n\r\n#### Observed Results:\r\n\r\n  * What happened?\r\n\r\nhttps://asciinema.org/a/H5fTY5spiv3Pl8UeDrGd9Xqgj\r\n\r\n#### Expected Results:\r\n\r\n  * What did you expect to happen?\r\n\r\nTo sign and publish my site", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1558677943, "modified": 1566204331, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2030", "source_type": "github"}]}