{"cert_user_id": "peter-tank@github", "next_comment_id": 8, "comment": {"1604065804_mirrored_PeterSurda_github": [{"comment_id": 1, "body": "zeronet now support plugins online install,may someone there wants give a try in py3.\nhttp://127.0.0.1:43110/1GbAj9ELv9XJSjLHA3eTSYN5gniWoVCrku/", "added": 1565692613, "modified": 1565692613, "source_link": "https://github.com/HelloZeroNet/ZeroNet/pull/852#issuecomment-520837625", "source_type": "github"}], "1604067440_mirrored_peter-tank_github": [{"comment_id": 2, "body": "@HelloZeroNet Thanks for the details, fixed now:\n  > INFO     - Libsecpk256k1 loaded: CompiledLib in 0.969s\n\n", "added": 1565761274, "modified": 1565761274, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2143#issuecomment-521157303", "source_type": "github"}], "1604067443_mirrored_peter-tank_github": [{"comment_id": 3, "body": "@HelloZeroNet U got one, but error in BroadcastServer remains, just OK with it or is resolving it on another issue? Am i missing some point in configure, bcz no such error in my centos system that configured with external ip.\n  > ERROR BroadcastServer Unable to listen on port 1544", "added": 1565833469, "modified": 1565833469, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2144#issuecomment-521511712", "source_type": "github"}, {"comment_id": 4, "body": "Tanks for your times spends on this great project.", "added": 1566048598, "modified": 1566048598, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2144#issuecomment-522251584", "source_type": "github"}], "1604067445_mirrored_peter-tank_github": [{"comment_id": 5, "body": "resolved after update to: https://github.com/HelloZeroNet/ZeroNet/commit/f5829f60122bd1ea25a92be142820091194e136d", "added": 1570522711, "modified": 1570522711, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2145#issuecomment-539467173", "source_type": "github"}], "1604067473_mirrored_tianlichunhong_github": [{"comment_id": 6, "body": "@tianlichunhong works for me:\n```\n\t\tproxy_set_header Host 127.0.0.1;\n\t\tproxy_set_header Origin http://127.0.0.1;\n```", "added": 1566332653, "modified": 1566332653, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2168#issuecomment-523233113", "source_type": "github"}], "1604067479_mirrored_tianlichunhong_github": [{"comment_id": 7, "body": "Have you ever enabled the Multiuser plugin?\nYou can bind ZeroNet to 127.0.0.1 then share it with port mapping progs (such as dokodemo-door protocol offerred by [V2Ray](https://v2ray.com/chapter_02/protocols/dokodemo.html), but I did'nt find any GUI's support customed inbound configuration till now), assuming you want keep your ZeroNet Proxy in private.", "added": 1566366970, "modified": 1566366989, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2171#issuecomment-523364697", "source_type": "github"}]}, "next_topic_id": 4, "topic": [{"topic_id": 1604067440, "title": "failed loading Libsecp256k1 and OpenSSL lib, under termux, falling back to slow bitcoin verify.", "body": "---\nname: Bug report\nabout: Create a report to help us improve ZeroNet\ntitle: 'failed loading Libsecp256k1 and OpenSSL lib, under termux, falling back to slow bitcoin verify.'\nlabels: 'Libsecp256k1, OpenSSL, termux'\nassignees: ''\n\n---\n\n### Step 1: Please describe your environment\n\n  * ZeroNet version: rev4176\n  * Operating system: android (aarch64)\n  * Web browser: Firefox, Chrome\n  * Tor status: disabled\n  * Opened port: yes\n  * Special configuration: `--ui_ip \"127.0.0.1 --proxy 127.0.0.1:1080 --trackers_proxy 127.0.0.1:1080 --ip_external <external_ipaddress>`\n\n### Step 2: Describe the problem:\n\n#### Steps to reproduce:\n\n  1. apt install python\n  2. make install [Libsecp256k1](https://github.com/bitcoin-core/secp256k1){commit fa3301713549d118e57ebe6551d062903ddd6b63}\n  3. make install [OpenSSL](https://www.openssl.org/source/openssl-1.0.2s.tar.gz)\n  4. apt install virtualenv\n  5. virtualenv --system-site-packages --no-download --python=python3.7 \"zeronet_py3\"\n  6. source \"zeronet_py3/bin/activate\"\n  7. pip install -r \"${pwd}/ZeroNet-py3/requirements.txt\"\n  8. pip list\n```Package           Version  \n----------------- ---------\nasn1crypto        0.24.0   \nbase58            1.0.3    \nbencode.py        2.1.0    \ncertifi           2019.6.16\ncffi              1.12.3   \nchardet           3.0.4    \ncoincurve         12.0.0   \ngevent            1.4.0    \ngevent-websocket  0.10.1   \ngreenlet          0.4.15   \nidna              2.8      \nlibsecp256k1      0.1      \nmaxminddb         1.4.1    \nmerkletools       1.0.3    \nmsgpack           0.6.1    \npip               19.2.1   \npyasn1            0.4.6    \npycparser         2.19     \npyelliptic        1.5.6    \npysha3            1.0.2    \nPySocks           1.7.0    \npython-bitcoinlib 0.10.1   \nrsa               4.0      \nsetuptools        41.0.1   \nsix               1.12.0   \nurllib3           1.25.3   \nvirtualenv        16.7.2   \nwebsocket-client  0.56.0   \nwheel             0.33.4\n```\n\n#### Observed Results:\n\n  * (zeronet_py3) $\n    > `python -V`\n    > Python 3.7.4\n    > `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`\n    > OpenSSL 1.1.1c  28 May 2019\n    > `\n  * start zeronet in DEBUG mode\n    > Watchdog fs listener could not be loaded: No module named 'watchdog'\n    > PluginManager Loading plugin: CryptMessage (builtin)\n    > WARNING: linker: /data/data/com.termux/files/home/zeronet_py3/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x2f8\n    > WARNING: linker: libsecp256k1.so.0: unused DT entry: type 0x6ffffef5 arg 0x300\n    > Libsecp256k1 load failed: dlopen failed: cannot locate symbol \"secp256k1_ecdsa_recoverable_signature_convert\" referenced by \"/data/data/com.termux/files/home/zeronet_py3/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m.so\"..., try to load OpenSSL\n    > OpenSSL lib not found in: /data/data/com.termux/files/usr/lib (list index out of range)\n    > Gevent block checker started\n    > OpenSSL load failed: undefined symbol: SSLeay, falling back to slow bitcoin verify\n\n#### Expected Results:\n\n  * \"Slow verifycation library\" warnings in ZeroHello Page.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1565751383, "modified": 1565761361, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2143", "source_type": "github"}, {"topic_id": 1604067443, "title": "failed in BroadcastServer: AttributeError: 'super' object has no attribute 'bind' in AnnounceLocal/BroadcastServer.py line 34 > socks.py line 340, retry #0", "body": "---\nname: Bug report\nabout: Create a report to help us improve ZeroNet\ntitle: \"failed in BroadcastServer: AttributeError: 'super' object has no attribute 'bind' in AnnounceLocal/BroadcastServer.py line 34 > socks.py line 340, retry #0\"\nlabels: 'BroadcastServer, termux'\nassignees: ''\n\n---\n\n### Step 1: Please describe your environment\n\n  * ZeroNet version: rev4176\n  * Operating system: android (aarch64)\n  * Web browser: Firefox, Chrome\n  * Tor status: disabled\n  * Opened port: yes\n  * Special configuration: `--ui_ip \"127.0.0.1 --proxy 127.0.0.1:1080 --trackers_proxy 127.0.0.1:1080 --ip_external <external_ipaddress>`\n\n### Step 2: Describe the problem:\n\n#### Steps to reproduce:\n\n  1. apt install python\n  2. make install [Libsecp256k1](https://github.com/bitcoin-core/secp256k1){commit fa3301713549d118e57ebe6551d062903ddd6b63}\n  3. make install [OpenSSL](https://www.openssl.org/source/openssl-1.0.2s.tar.gz)\n  4. apt install virtualenv\n  5. virtualenv --system-site-packages --no-download --python=python3.7 \"zeronet_py3\"\n  6. source \"zeronet_py3/bin/activate\"\n  7. pip install -r \"${pwd}/ZeroNet-py3/requirements.txt\"\n  8. pip list\n```Package           Version  \n----------------- ---------\nasn1crypto        0.24.0   \nbase58            1.0.3    \nbencode.py        2.1.0    \ncertifi           2019.6.16\ncffi              1.12.3   \nchardet           3.0.4    \ncoincurve         12.0.0   \ngevent            1.4.0    \ngevent-websocket  0.10.1   \ngreenlet          0.4.15   \nidna              2.8      \nlibsecp256k1      0.1      \nmaxminddb         1.4.1    \nmerkletools       1.0.3    \nmsgpack           0.6.1    \npip               19.2.1   \npyasn1            0.4.6    \npycparser         2.19     \npyelliptic        1.5.6    \npysha3            1.0.2    \nPySocks           1.7.0    \npython-bitcoinlib 0.10.1   \nrsa               4.0      \nsetuptools        41.0.1   \nsix               1.12.0   \nurllib3           1.25.3   \nvirtualenv        16.7.2   \nwebsocket-client  0.56.0   \nwheel             0.33.4\n```\n\n\n#### Observed Results:\n\n  * (zeronet_py3) $\n    > `python -V`\n    > Python 3.7.4\n    > `python -c 'import ssl; print(ssl.OPENSSL_VERSION)'`\n    > OpenSSL 1.1.1c  28 May 2019\n    > `\n  * start zeronet in DEBUG mode\n    > Watchdog fs listener could not be loaded: No module named 'watchdog'\n    >  DEBUG    ConnServer Conn# 4 100.36.xxx.xx [?] > Closing connection: 100.36.xxx.xx Connect error: ModuleNotFoundError: No module named 'lib.PySocks' in ConnectionServer.py line 208 > Connection.py line 132, waiting_requests: 0, sites: 0, buff: 0...\n    > INFO     - Creating FileServer....\n    > ERROR    FileServer IPv6 check error: 'super' object has no attribute 'bind'\n    > DEBUG    ConnServer Supported IP types: ['ipv4']\n    > DEBUG    BroadcastServer Sending discover request (force: False)\n    > DEBUG    BroadcastServer Broadcast using ips ['192.168.x.xxx'] on port 1544: discoverRequest\n    > WARNING  BroadcastServer Error sending broadcast using ip 192.168.x.xxx: 'super' object has no attribute 'bind'\n    > ERROR    BroadcastServer Socket bind to :1544 error: AttributeError: 'super' object has no attribute 'bind' in AnnounceLocal/BroadcastServer.py line 34 > socks.py line 340, retry #0\n\n#### Expected Results:\n\n  * No such errors.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1565752934, "modified": 1566048598, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2144", "source_type": "github"}, {"topic_id": 1604067445, "title": "Unhandled exception <ContentDbPlugin.py loadFilesOptional KeyError> on siteNeedFile cmd start", "body": "---\nname: Bug report\nabout: Create a report to help us improve ZeroNet\ntitle: 'Unhandled exception <ContentDbPlugin.py loadFilesOptional KeyError> on siteNeedFile only from cmdline.'\nlabels: 'siteNeedFile, cmdline'\nassignees: ''\n\n---\n\n### Step 1: Please describe your environment\n\n  * ZeroNet version: rev4176\n  * Operating system: centos6\n  * Web browser: None\n  * Tor status: disabled\n  * Opened port: yes\n  * Special configuration: None\n\n### Step 2: Describe the problem:\n\n#### Steps to reproduce:\n\n  1. excuted from shell `python3.7 ./zeronet.py --silent --log_level ERROR siteNeedFile \"<source_site_address>\" \"<site_file_path>\"`.\n\n#### Observed Results:\n\n  * start zeronet siteNeedFile cmd, exceptions not on each run:\n    > - Unhandled exception: [(<class 'KeyError'>, KeyError('1BwWMbqLbQPks7s1DN3d3zLEkMXvJqQijP'), <traceback object at 0x7f587062cc80>)]\n    > Traceback (most recent call last):\n  File \"src/gevent/greenlet.py\", line 766, in gevent._greenlet.Greenlet.run\n  File \"/root/zeronet/ZeroNet-py3/plugins/OptionalManager/ContentDbPlugin.py\", line 97, in loadFilesOptional\n    site = self.sites[site_address]\nKeyError: '1BwWMbqLbQPks7s1DN3d3zLEkMXvJqQijP'\n\n#### Expected Results:\n\n  * No such error.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1565764951, "modified": 1570522716, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/2145", "source_type": "github"}]}