{"cert_user_id": "hThoreau@github", "next_topic_id": 2, "topic": [{"topic_id": 1604066128, "title": "Running Zeronet using Subgraph", "body": "Hi.\r\n\r\nI'm trying to run Zeronet on a laptop using [Subgraph OS](https://subgraph.com/), the self-proclaimed _adversary resistant computing platform_. It's an operational system based on Debian and, much like its privacy oriented counterpart Tails OS, it uses what it refers to as a \"metaproxy\" in order to route all traffic through tor.\r\n\r\nI've installed Zeronet following the installation instructions provided for Debian, also, I've downloaded the required dependencies from their official repository. The installation process runs without errors, though ultimately Zeronet fails to launch:\r\n```\r\nuser@subgraph:~$ python ZeroNet-master/zeronet.py \r\n- Starting ZeroNet...\r\n[15:07:04] - OpenSSL loaded, version: 0100020CF\r\n[15:07:04] - Version: 0.5.7 r2190, Python 2.7.13 (default, Jan 19 2017, 14:48:08) \r\n[GCC 6.3.0 20170118], Gevent: 1.1.2\r\n[15:07:04] - Creating FileServer....\r\n[15:07:04] TorManager Connecting to Tor Controller 127.0.0.1:9051\r\n^CShutting down...\r\n[15:14:14] - Unhandled exception\r\nNone\r\nKeyboardInterrupt\r\n```\r\n\r\nI've sought and found attempts to troubleshoot this problem here at [Github](https://github.com/HelloZeroNet/ZeroNet/issues/610) and [Reddit](https://github.com/HelloZeroNet/ZeroNet/issues/610). Though they were experienced by users of Tails. Still, I tried the solution proposed unanimouslyby both treads.\r\n\r\n> I have installed Tails in a VM and this one worked for me:\r\n> \r\n> zeronet.py --proxy 127.0.0.1:9050 --tor disable --ui_ip 10.0.2.16 (your ip can be different from this use /sbin/ifconfig to see yours)\r\n> \r\n> Then access using http://10.0.2.16:43110\r\n\r\nThese are my network interfaces as described by ifconfig:\r\n```\r\nenp2s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500\r\n        ether c4:34:8f:ab:db:34  txqueuelen 1000  (Ethernet)\r\n        RX packets 0  bytes 0 (0.0 B)\r\n        RX errors 0  dropped 0  overruns 0  frame 0\r\n        TX packets 0  bytes 0 (0.0 B)\r\n        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0\r\n\r\nlo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536\r\n        inet 127.0.0.1  netmask 255.0.0.0\r\n        loop  txqueuelen 1  (Local Loopback)\r\n        RX packets 99129  bytes 33654317 (32.0 MiB)\r\n        RX errors 0  dropped 0  overruns 0  frame 0\r\n        TX packets 99129  bytes 33654317 (32.0 MiB)\r\n        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0\r\n\r\noz-clear: flags=67<UP,BROADCAST,RUNNING>  mtu 1500\r\n        inet 10.0.1.1  netmask 255.255.255.0  broadcast 0.0.0.0\r\n        ether aa:da:88:8d:6e:93  txqueuelen 1000  (Ethernet)\r\n        RX packets 25808  bytes 2604749 (2.4 MiB)\r\n        RX errors 0  dropped 0  overruns 0  frame 0\r\n        TX packets 35411  bytes 52660576 (50.2 MiB)\r\n        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0\r\n\r\nvozTJcEyg: flags=67<UP,BROADCAST,RUNNING>  mtu 1500\r\n        ether aa:da:88:8d:6e:93  txqueuelen 0  (Ethernet)\r\n        RX packets 18702  bytes 2125764 (2.0 MiB)\r\n        RX errors 0  dropped 0  overruns 0  frame 0\r\n        TX packets 26381  bytes 43486281 (41.4 MiB)\r\n        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0\r\n\r\nwlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500\r\n        inet 192.168.0.18  netmask 255.255.255.0  broadcast 192.168.0.255\r\n        ether 3c:97:0f:79:86:a0  txqueuelen 1000  (Ethernet)\r\n        RX packets 73846  bytes 84383411 (80.4 MiB)\r\n        RX errors 0  dropped 0  overruns 0  frame 0\r\n        TX packets 52848  bytes 12957734 (12.3 MiB)\r\n        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0\r\n```\r\nHence I tried the following command:\r\n```\r\nuser@subgraph:~$ python ZeroNet-master/zeronet.py --proxy 127.0.0.1:9050 --tor disable --ui_ip 10.0.1.1\r\n- Starting ZeroNet...\r\n[15:37:47] - OpenSSL loaded, version: 0100020CF\r\n[15:37:47] - Patching sockets to socks proxy: 127.0.0.1:9050\r\n[15:37:47] - Version: 0.5.7 r2190, Python 2.7.13 (default, Jan 19 2017, 14:48:08) \r\n[GCC 6.3.0 20170118], Gevent: 1.1.2\r\n[15:37:47] - Creating FileServer....\r\n[15:37:47] - Creating UiServer....\r\n[15:37:47] - Removing old SSL certs...\r\n[15:37:47] - Starting servers....\r\n[15:37:47] Ui.UiServer --------------------------------------\r\n[15:37:47] Ui.UiServer Web interface: http://10.0.1.1:43110/\r\n[15:37:47] Ui.UiServer --------------------------------------\r\n[15:37:48] FileServer Checking port 15441 using P2P...\r\n[15:37:48] FileServer Checking port 15441 using portchecker.co...\r\n[15:37:52] FileServer [BAD :(] Port closed: Port 15441 is closed.\r\n[15:37:52] FileServer Trying to open port using UpnpPunch...\r\n[15:38:08] FileServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 15441 on local machine after 3 tries. in FileServer.py line 75 > UpnpPunch.py line 325 > UpnpPunch.py line 316\r\n^CShutting down...\r\n[15:38:37] - Unhandled exception\r\nNone\r\nKeyboardInterrupt\r\n```\r\nStill, using both the Tor Browser and the clearnet enabled Chromium, the web interface failed to load. Also, I've checked my router configuration to make sure that it is fowarding port 15441, though I'm  not sure if it that's a relevant factor if not for publishing content at the Zeronet.\r\n\r\nI tried running the same command modified like so `python ZeroNet-master/zeronet.py --proxy 10.0.1.1:9050 --tor disable`, and I've got a slightly different response from the terminal running the command after the `FileServer [BAD :(]` part:\r\n```\r\n[16:05:51] FileServer [BAD :(] Port closed: Error: GeneralProxyError: Socket error: [Errno 104] Connection reset by peer in FileServer.py line 137 > urllib2.py line 154 > urllib2.py line 429 > urllib2.py line 447 > urllib2.py line 407 > urllib2.py line 1241 > urllib2.py line 1195 > httplib.py line 1042 > httplib.py line 1082 > httplib.py line 1038 > httplib.py line 882 > httplib.py line 844 > httplib.py line 1255 > httplib.py line 821 > SocksProxy.py line 12 > socks.py line 685\r\n[16:05:51] FileServer Trying to open port using UpnpPunch...\r\n[16:06:06] FileServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 15441 on local machine after 3 tries. in FileServer.py line 75 > UpnpPunch.py line 325 > UpnpPunch.py line 316\r\n^CShutting down...\r\n[16:06:37] - Unhandled exception\r\nNone\r\nKeyboardInterrupt\r\n```\r\nAlso, while performing these tests, I've had another terminal side-by-side running the command `sudo journalctl -f`. This terminal did not respond to the requests performed by executing `zeronet.py` before. Though, now it did:\r\n```\r\nSep 04 16:05:44 subgraph sudo[4422]: pam_unix(sudo:session): session opened for user root by (uid=0)\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 21f0 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45170 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 21f3 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45172 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 21f6 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45174 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 21f9 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45176 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 21fc ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45178 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 21ff ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45180 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph fw-daemon[750]: NOTI 2202 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45182 -> 10.0.1.1:9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:50 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:51 subgraph fw-daemon[750]: NOTI 220c ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45198 -> 10.0.1.1:9050\r\nSep 04 16:05:51 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:51 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:51 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:53 subgraph fw-daemon[750]: NOTI 2212 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45202 -> 10.0.1.1:9050\r\nSep 04 16:05:53 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:53 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:53 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\nSep 04 16:05:53 subgraph fw-daemon[750]: NOTI 2216 ALLOW|10.0.1.1:9050 > /usr/bin/python2.7 TCP 10.0.1.1:45206 -> 10.0.1.1:9050\r\nSep 04 16:05:53 subgraph subgraph-metaproxy[901]: No specific policy for client destination port, using wildcard relay for port: 9050\r\nSep 04 16:05:53 subgraph subgraph-metaproxy[901]: Opening SOCKS5 relay.\r\nSep 04 16:05:53 subgraph subgraph-metaproxy[901]: Error dialing SOCKS5 proxy at 127.0.0.1:9050: proxy: SOCKS5 proxy at 127.0.0.1:9050 failed to connect: general failure\r\n[...]\r\n```\r\nIt then goes on and on trying different ports to make a TCP connection and failing to do so.\r\n\r\nWell. That's it, that's all I know. Any guidance from here will be appreciated.\r\n\r\nThanks!", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1504541776, "modified": 1504634749, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1109", "source_type": "github"}], "next_comment_id": 4, "comment": {"1604066128_mirrored_hThoreau_github": [{"comment_id": 1, "body": "Here @skwerlman:\r\n```\r\nuser@subgraph:~$ python ZeroNet-master/zeronet.py --debug\r\n- Starting ZeroNet...\r\n[18:55:16] PluginManager Loading plugin: AnnounceZero\r\n[18:55:16] PluginManager New plugin registered to: Site\r\n[18:55:16] PluginManager Loading plugin: Cors\r\n[18:55:16] - Translate file not exists: src/Translate/languages/en.json\r\n[18:55:16] - Translate file not exists: plugins/Cors/languages/en.json\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager Loading plugin: CryptMessage\r\n[18:55:16] - Opening libssl.so.1.0.2...\r\n[18:55:16] - Disabled SSL compression on <CDLL 'libssl.so.1.0.2', handle 51eefbaf20 at 36809fe0f10>\r\n[18:55:16] - Missing SSLwrap, readded.\r\n[18:55:16] - Python SSL version: OpenSSL 1.1.0f  25 May 2017\r\n[18:55:16] - opensslVerify loaded: <CDLL 'libssl.so.1.0.2', handle 51eefbaf20 at 36809fca250>\r\n[18:55:16] - OpenSSL loaded, version: 0100020CF\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] PluginManager New plugin registered to: User\r\n[18:55:16] PluginManager Loading plugin: FilePack\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager New plugin registered to: SiteStorage\r\n[18:55:16] PluginManager Loading plugin: MergerSite\r\n[18:55:16] PluginManager New plugin registered to: ContentDb\r\n[18:55:16] PluginManager New plugin registered to: WorkerManager\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager New plugin registered to: FileRequest\r\n[18:55:16] PluginManager New plugin registered to: Site\r\n[18:55:16] PluginManager New plugin registered to: ConfigPlugin\r\n[18:55:16] - Translate file not exists: plugins/OptionalManager/languages/en.json\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] - Translate file not exists: plugins/MergerSite/languages/en.json\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager New plugin registered to: SiteStorage\r\n[18:55:16] PluginManager New plugin registered to: Site\r\n[18:55:16] PluginManager New plugin registered to: SiteManager\r\n[18:55:16] PluginManager Loading plugin: Mute\r\n[18:55:16] - Translate file not exists: plugins/Mute/languages/en.json\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] PluginManager New plugin registered to: SiteStorage\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager Loading plugin: Newsfeed\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] PluginManager New plugin registered to: User\r\n[18:55:16] PluginManager Loading plugin: OptionalManager\r\n[18:55:16] PluginManager Loading plugin: PeerDb\r\n[18:55:16] PluginManager New plugin registered to: ContentDb\r\n[18:55:16] PluginManager Loading plugin: Sidebar\r\n[18:55:16] - Translate file not exists: plugins/Sidebar/languages/en.json\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager New plugin registered to: UiWebsocket\r\n[18:55:16] PluginManager Loading plugin: Stats\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager Loading plugin: TranslateSite\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager Loading plugin: Trayicon\r\n[18:55:16] PluginManager Loading plugin: Zeroname\r\n[18:55:16] PluginManager New plugin registered to: UiRequest\r\n[18:55:16] PluginManager New plugin registered to: ConfigPlugin\r\n[18:55:16] PluginManager New plugin registered to: SiteManager\r\n[18:55:16] PluginManager New class accepts plugins: ConfigPlugin (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.ConfigPlugin'>, <class 'OptionalManager.OptionalManagerPlugin.ConfigPlugin'>, <class 'Config.ConfigPlugin'>])\r\n[18:55:16] - Config: Config(action='main', batch=False, bind=None, bit_resolver='1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F', coffeescript_compiler=None, config_file='zeronet.conf', connected_limit=8, data_dir='data', db_mode='speed', debug=True, debug_gevent=False, debug_socket=False, disable_db=False, disable_encryption=False, disable_sslcompression=True, disable_udp=False, download_optional='manual', end=True, file_size_limit=10, fileserver_ip='*', fileserver_port=15441, fix_float_decimals=False, homepage='1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D', ip_external=None, ip_local=['127.0.0.1'], keep_ssl_cert=False, language='en', log_dir='log', max_files_opened=2048, msgpack_purepython=False, open_browser=None, optional_limit='10%', proxy=None, silent=False, size_limit=10, stack_size=None, stream_downloads=False, tor='enable', tor_controller='127.0.0.1:9051', tor_hs_limit=10, tor_password=None, tor_proxy='127.0.0.1:9050', trackers=['zero://boot3rdez4rzn36x.onion:15441', 'zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710', 'http://tracker.opentrackr.org:1337/announce', 'http://explodie.org:6969/announce', 'http://tracker1.wasabii.com.tw:6969/announce'], trackers_file=False, ui_host=None, ui_ip='127.0.0.1', ui_port=43110, ui_restrict=False, updatesite='1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp', use_openssl=True, use_tempfiles=False, verbose=False, workers=5)\r\n[18:55:16] - Version: 0.5.7 r2190, Python 2.7.13 (default, Jan 19 2017, 14:48:08) \r\n[GCC 6.3.0 20170118], Gevent: 1.1.2\r\n[18:55:16] PluginManager New class accepts plugins: FileRequest (Loaded plugins: [<class 'OptionalManager.OptionalManagerPlugin.FileRequestPlugin'>, <class 'File.FileRequest.FileRequest'>])\r\n[18:55:16] PluginManager New class accepts plugins: WorkerManager (Loaded plugins: [<class 'OptionalManager.OptionalManagerPlugin.WorkerManagerPlugin'>, <class 'Worker.WorkerManager.WorkerManager'>])\r\n[18:55:16] PluginManager New class accepts plugins: ContentDb (Loaded plugins: [<class 'PeerDb.PeerDbPlugin.ContentDbPlugin'>, <class 'OptionalManager.ContentDbPlugin.ContentDbPlugin'>, <class 'Content.ContentDb.ContentDb'>])\r\n[18:55:16] Db:ContentDb Connected to data/content.db in 0.009s (opened: 1, sqlite version: 2.6.0)...\r\n[18:55:16] Db:ContentDb Db check done in 0.000s, changed tables: []\r\n[18:55:16] PluginManager New class accepts plugins: SiteStorage (Loaded plugins: [<class 'Mute.MutePlugin.SiteStoragePlugin'>, <class 'MergerSite.MergerSitePlugin.SiteStoragePlugin'>, <class 'FilePack.FilePackPlugin.SiteStoragePlugin'>, <class 'Site.SiteStorage.SiteStorage'>])\r\n[18:55:16] PluginManager New class accepts plugins: SiteManager (Loaded plugins: [<class 'Zeroname.SiteManagerPlugin.SiteManagerPlugin'>, <class 'MergerSite.MergerSitePlugin.SiteManagerPlugin'>, <class 'Site.SiteManager.SiteManager'>])\r\n[18:55:16] SiteManager SiteManager created.\r\n[18:55:16] PluginManager New class accepts plugins: Site (Loaded plugins: [<class 'MergerSite.MergerSitePlugin.SitePlugin'>, <class 'OptionalManager.OptionalManagerPlugin.SitePlugin'>, <class 'AnnounceZero.AnnounceZeroPlugin.SitePlugin'>, <class 'Site.Site.Site'>])\r\n[18:55:16] PluginManager New class accepts plugins: User (Loaded plugins: [<class 'Newsfeed.NewsfeedPlugin.UserPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UserPlugin'>, <class 'User.User.User'>])\r\n[18:55:16] PluginManager New class accepts plugins: UiWebsocket (Loaded plugins: [<class 'Sidebar.SidebarPlugin.UiWebsocketPlugin'>, <class 'Newsfeed.NewsfeedPlugin.UiWebsocketPlugin'>, <class 'Mute.MutePlugin.UiWebsocketPlugin'>, <class 'MergerSite.MergerSitePlugin.UiWebsocketPlugin'>, <class 'OptionalManager.UiWebsocketPlugin.UiWebsocketPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UiWebsocketPlugin'>, <class 'Cors.CorsPlugin.UiWebsocketPlugin'>, <class 'Ui.UiWebsocket.UiWebsocket'>])\r\n[18:55:16] PluginManager New class accepts plugins: UiRequest (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.UiRequestPlugin'>, <class 'TranslateSite.TranslateSitePlugin.UiRequestPlugin'>, <class 'Stats.StatsPlugin.UiRequestPlugin'>, <class 'Sidebar.SidebarPlugin.UiRequestPlugin'>, <class 'Mute.MutePlugin.UiRequestPlugin'>, <class 'MergerSite.MergerSitePlugin.UiRequestPlugin'>, <class 'OptionalManager.OptionalManagerPlugin.UiRequestPlugin'>, <class 'FilePack.FilePackPlugin.UiRequestPlugin'>, <class 'Cors.CorsPlugin.UiRequestPlugin'>, <class 'Ui.UiRequest.UiRequest'>])\r\n[18:55:16] - Creating FileServer....\r\n[18:55:16] TorManager Connecting to Tor Controller 127.0.0.1:9051\r\n[18:55:16] TorManager > PROTOCOLINFO\r\n[18:55:16] TorManager 250-PROTOCOLINFO 1\r\n250-AUTH METHODS=NULL,HASHEDPASSWORD\r\n250-VERSION Tor=\"0.2.9.11\"\r\n250 OK\r\n\r\n[18:55:16] TorManager < 250-PROTOCOLINFO 1\r\n250-AUTH METHODS=NULL,HASHEDPASSWORD\r\n250-VERSION Tor=\"0.2.9.11\"\r\n250 OK\r\n[18:55:16] TorManager > AUTHENTICATE\r\n[18:55:16] TorManager 250 OK\r\n\r\n[18:55:16] TorManager < 250 OK\r\n[18:55:16] TorManager > GETINFO version\r\n[18:55:16] TorManager 510 Tor Control command proxy denied: filtration policy.\r\n\r\n[19:00:16] Db:ContentDb Optional size: 0.0MB/86750.9MB, Need delete: -86750.9MB\r\n[19:05:16] Db:ContentDb Optional size: 0.0MB/86777.1MB, Need delete: -86777.1MB\r\n[19:05:16] SiteManager Save skipped: No sites found\r\n[19:10:16] Db:ContentDb Optional size: 0.0MB/86777.8MB, Need delete: -86777.8MB\r\n```", "added": 1504551468, "modified": 1504552427, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1109#issuecomment-327032714", "source_type": "github"}, {"comment_id": 2, "body": "@skwerlman, yes, that was the case. I've read its documentation and was able to allow Zeronet to peform commands that where previously blocked, making its initialization process move further. Still, it is not yet complete.\r\n\r\nBy running ROFLcoptor in watch mode I was able to spot it blocking the Zeronet client attempt at connection. Here is the last output from the terminal launching Zeronet:\r\n```[00:49:23] TorManager Connecting to Tor Controller 127.0.0.1:9051```\r\nAnd a corresponding response in the terminal running ROFLcoptor:\r\n```2017/09/05 00:49:23 filter policy for gnome-shell-torstatus DENY: A->T: [GETINFO version]```\r\nI then modified the /etc/roflcoptor/filters/gnome-shell.json file and was able to pass this stage, eventually getting and error related to the command ADD_ONION. I then modified the file again reaching its current state:\r\n```\r\n{\r\n    \"Name\": \"gnome-shell-torstatus\",\r\n    \"AuthNetAddr\" : \"tcp\",\r\n    \"AuthAddr\" : \"127.0.0.1:9051\",\r\n    \"client-allowed\" : [\"GETINFO status/bootstrap-phase\", \"GETINFO version\", \"SIGNAL NEWNYM\"],\r\n    \"client-allowed-prefixes\" : [\"ADD_ONION\", \"DEL_ONION\"],\r\n    \"client-replacements\" : {},\r\n    \"client-replacement-prefixes\" : {},\r\n    \"server-allowed\" : [\"250 OK\", \"250 __OwningControllerProcess\"],\r\n    \"server-allowed-prefixes\" : [\"250-status/bootstrap-phase=\", \"250-version=\"],\r\n    \"server-replacement-prefixes\" : {}\r\n}\r\n```\r\n\r\nNow, when I run ROFLcoptor in watch mode, it does not point out to any blocked connections. Still, Zeronet's initialization is now stopping at this point:\r\n```\r\nuser@subgraph:~$ python ZeroNet-master/zeronet.py --debug\r\n- Starting ZeroNet...\r\n[14:24:15] PluginManager Loading plugin: AnnounceZero\r\n[14:24:15] PluginManager New plugin registered to: Site\r\n[14:24:15] PluginManager Loading plugin: Cors\r\n[14:24:15] - Translate file not exists: src/Translate/languages/en.json\r\n[14:24:15] - Translate file not exists: plugins/Cors/languages/en.json\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager Loading plugin: CryptMessage\r\n[14:24:15] - Opening libssl.so.1.0.2...\r\n[14:24:15] - Disabled SSL compression on <CDLL 'libssl.so.1.0.2', handle 67d94663f0 at 31e31db8f10>\r\n[14:24:15] - Missing SSLwrap, readded.\r\n[14:24:15] - Python SSL version: OpenSSL 1.1.0f  25 May 2017\r\n[14:24:15] - opensslVerify loaded: <CDLL 'libssl.so.1.0.2', handle 67d94663f0 at 31e31da2250>\r\n[14:24:15] - OpenSSL loaded, version: 0100020CF\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] PluginManager New plugin registered to: User\r\n[14:24:15] PluginManager Loading plugin: FilePack\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager New plugin registered to: SiteStorage\r\n[14:24:15] PluginManager Loading plugin: MergerSite\r\n[14:24:15] PluginManager New plugin registered to: ContentDb\r\n[14:24:15] PluginManager New plugin registered to: WorkerManager\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager New plugin registered to: FileRequest\r\n[14:24:15] PluginManager New plugin registered to: Site\r\n[14:24:15] PluginManager New plugin registered to: ConfigPlugin\r\n[14:24:15] - Translate file not exists: plugins/OptionalManager/languages/en.json\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] - Translate file not exists: plugins/MergerSite/languages/en.json\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager New plugin registered to: SiteStorage\r\n[14:24:15] PluginManager New plugin registered to: Site\r\n[14:24:15] PluginManager New plugin registered to: SiteManager\r\n[14:24:15] PluginManager Loading plugin: Mute\r\n[14:24:15] - Translate file not exists: plugins/Mute/languages/en.json\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] PluginManager New plugin registered to: SiteStorage\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager Loading plugin: Newsfeed\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] PluginManager New plugin registered to: User\r\n[14:24:15] PluginManager Loading plugin: OptionalManager\r\n[14:24:15] PluginManager Loading plugin: PeerDb\r\n[14:24:15] PluginManager New plugin registered to: ContentDb\r\n[14:24:15] PluginManager Loading plugin: Sidebar\r\n[14:24:15] - Translate file not exists: plugins/Sidebar/languages/en.json\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager New plugin registered to: UiWebsocket\r\n[14:24:15] PluginManager Loading plugin: Stats\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager Loading plugin: TranslateSite\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager Loading plugin: Trayicon\r\n[14:24:15] PluginManager Loading plugin: Zeroname\r\n[14:24:15] PluginManager New plugin registered to: UiRequest\r\n[14:24:15] PluginManager New plugin registered to: ConfigPlugin\r\n[14:24:15] PluginManager New plugin registered to: SiteManager\r\n[14:24:15] PluginManager New class accepts plugins: ConfigPlugin (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.ConfigPlugin'>, <class 'OptionalManager.OptionalManagerPlugin.ConfigPlugin'>, <class 'Config.ConfigPlugin'>])\r\n[14:24:15] - Config: Config(action='main', batch=False, bind=None, bit_resolver='1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F', coffeescript_compiler=None, config_file='zeronet.conf', connected_limit=8, data_dir='data', db_mode='speed', debug=True, debug_gevent=False, debug_socket=False, disable_db=False, disable_encryption=False, disable_sslcompression=True, disable_udp=False, download_optional='manual', end=True, file_size_limit=10, fileserver_ip='*', fileserver_port=15441, fix_float_decimals=False, homepage='1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D', ip_external=None, ip_local=['127.0.0.1'], keep_ssl_cert=False, language='en', log_dir='log', max_files_opened=2048, msgpack_purepython=False, open_browser=None, optional_limit='10%', proxy=None, silent=False, size_limit=10, stack_size=None, stream_downloads=False, tor='enable', tor_controller='127.0.0.1:9051', tor_hs_limit=10, tor_password=None, tor_proxy='127.0.0.1:9050', trackers=['zero://boot3rdez4rzn36x.onion:15441', 'zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710', 'http://tracker.opentrackr.org:1337/announce', 'http://explodie.org:6969/announce', 'http://tracker1.wasabii.com.tw:6969/announce'], trackers_file=False, ui_host=None, ui_ip='127.0.0.1', ui_port=43110, ui_restrict=False, updatesite='1UPDatEDxnvHDo7TXvq6AEBARfNkyfxsp', use_openssl=True, use_tempfiles=False, verbose=False, workers=5)\r\n[14:24:15] - Version: 0.5.7 r2190, Python 2.7.13 (default, Jan 19 2017, 14:48:08) \r\n[GCC 6.3.0 20170118], Gevent: 1.1.2\r\n[14:24:15] PluginManager New class accepts plugins: FileRequest (Loaded plugins: [<class 'OptionalManager.OptionalManagerPlugin.FileRequestPlugin'>, <class 'File.FileRequest.FileRequest'>])\r\n[14:24:15] PluginManager New class accepts plugins: WorkerManager (Loaded plugins: [<class 'OptionalManager.OptionalManagerPlugin.WorkerManagerPlugin'>, <class 'Worker.WorkerManager.WorkerManager'>])\r\n[14:24:15] PluginManager New class accepts plugins: ContentDb (Loaded plugins: [<class 'PeerDb.PeerDbPlugin.ContentDbPlugin'>, <class 'OptionalManager.ContentDbPlugin.ContentDbPlugin'>, <class 'Content.ContentDb.ContentDb'>])\r\n[14:24:15] Db:ContentDb Connected to data/content.db in 0.000s (opened: 1, sqlite version: 2.6.0)...\r\n[14:24:15] Db:ContentDb Db check done in 0.000s, changed tables: []\r\n[14:24:15] PluginManager New class accepts plugins: SiteStorage (Loaded plugins: [<class 'Mute.MutePlugin.SiteStoragePlugin'>, <class 'MergerSite.MergerSitePlugin.SiteStoragePlugin'>, <class 'FilePack.FilePackPlugin.SiteStoragePlugin'>, <class 'Site.SiteStorage.SiteStorage'>])\r\n[14:24:15] PluginManager New class accepts plugins: SiteManager (Loaded plugins: [<class 'Zeroname.SiteManagerPlugin.SiteManagerPlugin'>, <class 'MergerSite.MergerSitePlugin.SiteManagerPlugin'>, <class 'Site.SiteManager.SiteManager'>])\r\n[14:24:15] SiteManager SiteManager created.\r\n[14:24:15] PluginManager New class accepts plugins: Site (Loaded plugins: [<class 'MergerSite.MergerSitePlugin.SitePlugin'>, <class 'OptionalManager.OptionalManagerPlugin.SitePlugin'>, <class 'AnnounceZero.AnnounceZeroPlugin.SitePlugin'>, <class 'Site.Site.Site'>])\r\n[14:24:15] PluginManager New class accepts plugins: User (Loaded plugins: [<class 'Newsfeed.NewsfeedPlugin.UserPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UserPlugin'>, <class 'User.User.User'>])\r\n[14:24:15] PluginManager New class accepts plugins: UiWebsocket (Loaded plugins: [<class 'Sidebar.SidebarPlugin.UiWebsocketPlugin'>, <class 'Newsfeed.NewsfeedPlugin.UiWebsocketPlugin'>, <class 'Mute.MutePlugin.UiWebsocketPlugin'>, <class 'MergerSite.MergerSitePlugin.UiWebsocketPlugin'>, <class 'OptionalManager.UiWebsocketPlugin.UiWebsocketPlugin'>, <class 'CryptMessage.CryptMessagePlugin.UiWebsocketPlugin'>, <class 'Cors.CorsPlugin.UiWebsocketPlugin'>, <class 'Ui.UiWebsocket.UiWebsocket'>])\r\n[14:24:15] PluginManager New class accepts plugins: UiRequest (Loaded plugins: [<class 'Zeroname.UiRequestPlugin.UiRequestPlugin'>, <class 'TranslateSite.TranslateSitePlugin.UiRequestPlugin'>, <class 'Stats.StatsPlugin.UiRequestPlugin'>, <class 'Sidebar.SidebarPlugin.UiRequestPlugin'>, <class 'Mute.MutePlugin.UiRequestPlugin'>, <class 'MergerSite.MergerSitePlugin.UiRequestPlugin'>, <class 'OptionalManager.OptionalManagerPlugin.UiRequestPlugin'>, <class 'FilePack.FilePackPlugin.UiRequestPlugin'>, <class 'Cors.CorsPlugin.UiRequestPlugin'>, <class 'Ui.UiRequest.UiRequest'>])\r\n[14:24:15] - Creating FileServer....\r\n[14:24:15] TorManager Connecting to Tor Controller 127.0.0.1:9051\r\n[14:24:15] TorManager > PROTOCOLINFO\r\n[14:24:15] TorManager 250-PROTOCOLINFO 1\r\n250-AUTH METHODS=NULL,HASHEDPASSWORD\r\n250-VERSION Tor=\"0.2.9.11\"\r\n250 OK\r\n\r\n[14:24:15] TorManager < 250-PROTOCOLINFO 1\r\n250-AUTH METHODS=NULL,HASHEDPASSWORD\r\n250-VERSION Tor=\"0.2.9.11\"\r\n250 OK\r\n[14:24:15] TorManager > AUTHENTICATE\r\n[14:24:15] TorManager 250 OK\r\n\r\n[14:24:15] TorManager < 250 OK\r\n[14:24:15] TorManager > GETINFO version\r\n[14:24:15] TorManager 250-version=0.2.9.11 (git-572f4570e1771890)\r\n250 OK\r\n\r\n[14:24:15] TorManager < 250-version=0.2.9.11 (git-572f4570e1771890)\r\n250 OK\r\n[14:24:15] TorManager Tor proxy port 127.0.0.1:9050 check ok\r\n[14:24:15] - Creating UiServer....\r\n[14:24:15] SiteManager Sites not loaded yet...\r\n[14:24:15] SiteManager Loading sites...\r\n[14:24:15] Site:1Name2..hM9F ContentDb init: 0.000s, found files: 1, sites: 1\r\n[14:24:15] SiteManager Loaded site 1Name2NXVi1RDPDgf5617UoW7xA6YrhM9F in 0.001s\r\n[14:24:15] SiteManager SiteManager added 1 sites\r\n[14:24:15] SiteManager Updated merger sites in 0.000s\r\n[14:24:15] - Removing old SSL certs...\r\n[14:24:15] - Starting servers....\r\n[14:24:15] Ui.UiServer No module named werkzeug.debug: For debugging please download Werkzeug (http://werkzeug.pocoo.org/)\r\n[14:24:15] Ui.UiServer --------------------------------------\r\n[14:24:15] Ui.UiServer Web interface: http://127.0.0.1:43110/\r\n[14:24:15] Ui.UiServer --------------------------------------\r\n[14:24:15] - Current RLIMIT_NOFILE: 1024 (max: 4096), changing to 2048...\r\n[14:24:16] - Generating RSA cert and key PEM files...Generating a 2048 bit RSA private key\r\n.......................................................................................................................................................+++\r\n....+++\r\nunable to write 'random state'\r\nwriting new private key to 'data/key-rsa.pem'\r\n-----\r\n[14:24:16] FileServer Binding to: *:15441, (msgpack: 0.4.8), supported crypt: ['tls-rsa']\r\n[14:24:16] FileServer Checking sites...\r\n[14:24:16] FileServer Conn# 1 boot3rdez4rzn36x.onion [?] > Connecting...\r\n[14:24:16] TorManager Creating new Tor socket to boot3rdez4rzn36x.onion:15441\r\n[14:24:16] FileServer Conn# 2 boot.zeronet.io [?] > Connecting...\r\n[14:24:16] Site:1Name2..hM9F 303 peers (0 with hashfield) loaded in 0.005s\r\n[14:24:16] Db:ContentDb Loaded 0 optional files: 0.00MB, downloaded: 0.00MB in 0.000s\r\n[14:24:17] FileServer Checking port 15441 using P2P...\r\n[14:24:17] FileServer Checking port 15441 using portchecker.co...\r\n[14:24:26] Site:1Name2..hM9F Announced types [] in mode startup to 0 trackers in 10.003s, errors: ['udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969', 'udp://9.rarbg.com:2710'], slow: ['10s+ zero://boot3rdez4rzn36x.onion:15441', '10s+ zero://boot.zeronet.io#f36ca555bee6ba216b14d10f38c16f7769ff064e0e37d887603548cc2e64191d:15441', '10s+ http://tracker.opentrackr.org:1337/announce', '10s+ http://explodie.org:6969/announce', '10s+ http://tracker1.wasabii.com.tw:6969/announce']\r\n[14:24:26] Site:1Name2..hM9F content.json loadContent same json file, skipping\r\n[14:24:26] FileServer Conn# 3 210.219.231.5 [?] > Connecting...\r\n[14:24:26] FileServer Conn# 4 193.77.149.84 [?] > Connecting...\r\n[14:24:26] FileServer Conn# 5 51.39.85.183 [?] > Connecting...\r\n[14:24:26] FileServer Conn# 1 boot3rdez4rzn36x.onion [?] > Closing connection: boot3rdez4rzn36x.onion Connect error: SOCKS5Error: 0x04: Host unreachable in ConnectionServer.py line 142 > Connection.py line 100 > TorManager.py line 312 > socks.py line 681 > socks.py line 383 > socks.py line 458, waiting_requests: 0, sites: 0, buff: 0...\r\n[14:24:26] Site:1Name2..hM9F Announce to boot3rdez4rzn36x.onion:15441 failed: None\r\n[14:24:29] Site:1Name2..hM9F Small number of peers detected...query all of peers using pex\r\n[14:24:29] FileServer Conn# 6 82.119.233.36 [?] > Connecting...\r\n[14:24:34] Site:1Name2..hM9F Found 16 ip4, 4 onion peers, new: 17\r\n[14:24:34] FileServer Conn# 2 boot.zeronet.io [v2] > Closing connection: Removing, waiting_requests: 0, sites: 1, buff: 0...\r\n[14:24:38] Site:1Name2..hM9F Found 30 peers, new: 7, total: 327\r\n[14:24:39] FileServer Conn# 4 193.77.149.84 [v2] > Crypt out connection using: tls-rsa (server side: False, ping: 13.400s)...\r\n[14:24:40] FileServer Conn# 6 82.119.233.36 [v2] > Crypt out connection using: tls-rsa (server side: False, ping: 11.289s)...\r\n[14:24:42] FileServer Conn# 7 188.27.90.214 [?] > Connecting...\r\n[14:24:42] FileServer [BAD :(] Port closed: Port 15441 is closed.\r\n[14:24:42] FileServer Trying to open port using UpnpPunch...\r\n[14:24:42] - Trying to open port 15441.\r\n[14:24:43] - Found local ips: ['192.168.0.11']\r\n[14:24:43] - Trying using local ip: 192.168.0.11\r\n[14:24:43] FileServer Conn# 8 85.218.116.137 [?] > Connecting...\r\n[14:24:44] FileServer Conn# 7 188.27.90.214 [v2] > Crypt out connection using: tls-rsa (server side: False, ping: 2.594s)...\r\n[14:24:46] Site:1Name2..hM9F Http tracker tracker1.wasabii.com.tw:6969/announce error: local variable 'response' referenced before assignment\r\n[14:24:46] FileServer Conn# 9 2.99.187.27  [?] > Connecting...\r\n[14:24:46] FileServer Conn#10 24.6.245.4   [?] > Connecting...\r\n[14:24:46] Site:1Name2..hM9F Queried listModifications from: [<Peer:193.77.149.84>] in 20.003s\r\n[14:24:46] Site:1Name2..hM9F content.json loadContent same json file, skipping\r\n[14:24:46] Site:1Name2..hM9F Need connections: 4, Current: 8, Total: 330\r\n[14:24:46] FileServer Conn#11 218.98.33.33 [?] > Connecting...\r\n[14:24:48] - Upnp request using \"192.168.0.11\" failed: No reply from IGD using 192.168.0.11 as IP\r\n[14:24:48] - Trying using local ip: 192.168.0.11\r\n[14:24:50] FileServer Conn# 9 2.99.187.27  [v2] > Crypt out connection using: tls-rsa (server side: False, ping: 4.071s)...\r\n[14:24:53] - Upnp request using \"192.168.0.11\" failed: No reply from IGD using 192.168.0.11 as IP\r\n[14:24:53] - Trying using local ip: 192.168.0.11\r\n[14:24:58] - Upnp request using \"192.168.0.11\" failed: No reply from IGD using 192.168.0.11 as IP\r\n[14:24:58] FileServer UpnpPunch run error: UpnpError: Failed to communicate with igd using port 15441 on local machine after 3 tries. in FileServer.py line 75 > UpnpPunch.py line 325 > UpnpPunch.py line 316\r\n[14:24:58] TorManager Start onions\r\n[14:26:42] FileServer Conn# 3 210.219.231.5 [v2] > Socket error: error: [Errno 104] Connection reset by peer in Connection.py line 145 > _socket2.py line 274\r\n[14:26:42] FileServer Conn# 3 210.219.231.5 [v2] > Closing connection: MessageLoop ended, waiting_requests: 0, sites: 2, buff: 0...\r\n[14:26:46] FileServer Conn#11 218.98.33.33 [v2] > Socket error: error: [Errno 104] Connection reset by peer in Connection.py line 145 > _socket2.py line 274\r\n[14:26:46] FileServer Conn#11 218.98.33.33 [v2] > Closing connection: MessageLoop ended, waiting_requests: 0, sites: 0, buff: 0...\r\n[14:26:47] FileServer Conn# 5 51.39.85.183 [v2] > Socket error: error: [Errno 104] Connection reset by peer in Connection.py line 145 > _socket2.py line 274\r\n[14:26:47] FileServer Conn# 5 51.39.85.183 [v2] > Closing connection: MessageLoop ended, waiting_requests: 0, sites: 2, buff: 0...\r\n[14:26:51] FileServer Conn# 8 85.218.116.137 [v2] > Socket error: error: [Errno 104] Connection reset by peer in Connection.py line 145 > _socket2.py line 274\r\n[14:26:51] FileServer Conn# 8 85.218.116.137 [v2] > Closing connection: MessageLoop ended, waiting_requests: 0, sites: 1, buff: 0...\r\n[14:26:51] FileServer Conn#12 144.48.7.45  [?] > Connecting...\r\n[14:26:55] FileServer Conn#10 24.6.245.4   [v2] > Socket error: error: [Errno 104] Connection reset by peer in Connection.py line 145 > _socket2.py line 274\r\n[14:26:55] FileServer Conn#10 24.6.245.4   [v2] > Closing connection: MessageLoop ended, waiting_requests: 0, sites: 1, buff: 0...\r\n[14:27:00] FileServer Conn#12 144.48.7.45  [v2] > Crypt out connection using: tls-rsa (server side: False, ping: 9.743s)...\r\n[14:27:02] Site:1Name2..hM9F Queried pex from 2 peers got 6 new peers.\r\n[14:29:15] Db:ContentDb Optional size: 0.0MB/86800.9MB, Need delete: -86800.9MB\r\n[14:29:16] FileServer Running site cleanup, connections: 5, internet: True, protected peers: set([])\r\n[14:29:19] Site:1Name2..hM9F Queried pex from 2 peers got 4 new peers.\r\n[14:29:22] Site:1Name2..hM9F Announced types ['onion'] in mode update to 1 trackers in 6.280s, errors: [], slow: ['6.28s http://explodie.org:6969/announce']\r\n[14:29:22] Site:1Name2..hM9F Need connections: 4, Current: 5, Total: 337\r\n[14:29:23] FileServer Site announce tracker done in 7.280s, sleeping for 142.719527006s...\r\n^CShutting down...\r\n[14:29:40] Ui.UiServer Stopping...\r\n[14:29:40] Ui.UiServer Socket closed: 0\r\n[14:29:40] FileServer Stopped.\r\n[14:29:40] Ui.UiServer Stopped.\r\n[14:29:40] SiteManager Saved sites in 0.00s (generate: 0.00s, write: 0.00s)\r\n[14:29:40] SiteManager Updated merger sites in 0.000s\r\n[14:29:40] Site:1Name2..hM9F Peers saved in 0.002s\r\n```", "added": 1504623217, "modified": 1504623217, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1109#issuecomment-327254385", "source_type": "github"}, {"comment_id": 3, "body": "@HelloZeroNet I see... Then it must be due to the sandboxing configuration that the Tor Browser and Chromium are subject to by default under [Oz](https://github.com/subgraph/oz) that I wasn't able to access this page. I should see how to make the necessary exceptions and then edit this post with my findings.", "added": 1504634749, "modified": 1504634749, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/1109#issuecomment-327303244", "source_type": "github"}]}}