Traceback (most recent call last):
  File "/Users/eventi/zeronet/zeronet.py", line 15, in main
    import main
  File "/Users/eventi/zeronet/src/main.py", line 79, in <module>
    PluginManager.plugin_manager.loadPlugins()
  File "/Users/eventi/zeronet/src/Plugin/PluginManager.py", line 27, in loadPlugins
    for dir_name in os.listdir(self.plugin_path):
OSError: [Errno 2] No such file or directory: 'plugins'
