{"cert_user_id": "t4ec@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065162, "title": "Unhandled exception: Wrong encoding", "body": "Hello,\n\nWhile trying to open one site which dynamically loads content (images + text) I get following error and images/text are not loaded, so the site is partially broken.\n\nHere you can see the traceback:\n\n```\n[20:07:06] - Unhandled exception\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/gevent/greenlet.py\", line 327, in run\n    result = self._run(*self.args, **self.kwargs)\n  File \"src/Worker/Worker.py\", line 56, in downloader\n    correct = site.content_manager.verifyFile(task[\"inner_path\"], buff)\n  File \"src/Content/ContentManager.py\", line 594, in verifyFile\n    if inner_path != \"content.json\" and not self.verifyCert(inner_path, new_content):  # Check if cert valid\n  File \"src/Content/ContentManager.py\", line 475, in verifyCert\n    \"%s#%s/%s\" % (rules[\"user_address\"], content[\"cert_auth_type\"], name), cert_address, content[\"cert_sign\"]\n  File \"src/Crypt/CryptBitcoin.py\", line 63, in verify\n    pub = opensslVerify.getMessagePubkey(data, sign)\n  File \"src/lib/opensslVerify/opensslVerify.py\", line 422, in getMessagePubkey\n    eckey = SetCompactSignature(pkey, Hash(msg_magic(message)), sig)\n  File \"src/lib/opensslVerify/opensslVerify.py\", line 329, in SetCompactSignature\n    raise BaseException(\"Wrong encoding\")\nBaseException: Wrong encoding\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/gevent/greenlet.py\", line 327, in run\n    result = self._run(*self.args, **self.kwargs)\n  File \"src/Worker/Worker.py\", line 56, in downloader\n    correct = site.content_manager.verifyFile(task[\"inner_path\"], buff)\n  File \"src/Content/ContentManager.py\", line 594, in verifyFile\n    if inner_path != \"content.json\" and not self.verifyCert(inner_path, new_content):  # Check if cert valid\n  File \"src/Content/ContentManager.py\", line 475, in verifyCert\n    \"%s#%s/%s\" % (rules[\"user_address\"], content[\"cert_auth_type\"], name), cert_address, content[\"cert_sign\"]\n  File \"src/Crypt/CryptBitcoin.py\", line 63, in verify\n    pub = opensslVerify.getMessagePubkey(data, sign)\n  File \"src/lib/opensslVerify/opensslVerify.py\", line 422, in getMessagePubkey\n    eckey = SetCompactSignature(pkey, Hash(msg_magic(message)), sig)\n  File \"src/lib/opensslVerify/opensslVerify.py\", line 329, in SetCompactSignature\n    raise BaseException(\"Wrong encoding\")\nBaseException: Wrong encoding\n```\n\nI am still able to browse this and other sites, it's just some part of content which is not loaded.\nLet me know if you need additional information.\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1457363514, "modified": 1502790354, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/340", "source_type": "github"}]}