{"cert_user_id": "Wolden@github", "next_topic_id": 2, "topic": [{"topic_id": 1604065110, "title": "OS X 10.9 log/error.log not found", "body": "$ python zeronet.py\n- Starting ZeroNet...\n  .........\n  File \"zeronet.py\", line 46, in main\n  traceback.print_exc(file=open(\"log/error.log\", \"a\"))\n  IOError: [Errno 2] No such file or directory: 'log/error.log'\n\nno such dir or file in Zero-master. Where am I supposed to find it?\n", "parent_topic_uri": "1604062980_users_1Cy3ntkN2GN9MH6EaW6eHpi4YoRS2nK5Di", "added": 1456980159, "modified": 1480599623, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/301", "source_type": "github"}], "next_comment_id": 4, "comment": {"1604065110_mirrored_Wolden_github": [{"comment_id": 1, "body": "OK the log dir is now created. Next prob: \n  File \"/Zeronet/src/main.py\", line 8, in <module>\n    import gevent\nImportError: No module named gevent\n\nwhere's gevent?\n", "added": 1456991849, "modified": 1456991849, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/301#issuecomment-191706274", "source_type": "github"}, {"comment_id": 2, "body": "/usr/bin/python: No module named pip  oups.\n", "added": 1456995093, "modified": 1456995093, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/301#issuecomment-191723360", "source_type": "github"}, {"comment_id": 3, "body": "Sorry for being so long ... Everything seems to work perfectly :-) \n\nBenchmarking ZeroNet 0.3.6 (rev1069) Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec 6 2015, 18:57:58) [GCC 4.2.1 (Apple Inc. build 5577)] on: darwin...\n\nThx so much for all :-)\n", "added": 1458626459, "modified": 1458626459, "source_link": "https://github.com/HelloZeroNet/ZeroNet/issues/301#issuecomment-199707225", "source_type": "github"}]}}